####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
# It uses a micro base image, tuned for Quarkus native executables.
# It reduces the size of the resulting container image.
# Check https://quarkus.io/guides/quarkus-runtime-base-image for further information about this image.
#
# Before building the container image run:
#
# mvn package -Dnative -Dquarkus.native.container-build=true
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native-micro -t quarkus/task-manager-backend .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/task-manager-backend
#
# The `quay.io/quarkus/ubi9-quarkus-micro-image:2.0` base image is based on UBI 9.
# To use UBI 8, switch to `quay.io/quarkus/quarkus-micro-image:2.0`.
###
# Etapa 1: Build nativo
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /project
COPY . .
RUN mvn package -Dnative -Dquarkus.native.container-build=true -DskipTests

# Etapa 2: Runtime
FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work/
COPY --from=build /project/target/*-runner /work/application
RUN chmod 755 /work/application
USER 1001
EXPOSE 8080
ENTRYPOINT ["./application","-Dquarkus.http.host=0.0.0.0"]