####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
# It uses a micro base image, tuned for Quarkus native executables.
# It reduces the size of the resulting container image.
# Check https://quarkus.io/guides/quarkus-runtime-base-image for further information about this image.
#
# Before building the container image run:
#
# mvn package -Dnative -Dquarkus.native.container-build=true
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native-micro -t quarkus/task-manager-backend .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/task-manager-backend
#
# The `quay.io/quarkus/ubi9-quarkus-micro-image:2.0` base image is based on UBI 9.
# To use UBI 8, switch to `quay.io/quarkus/quarkus-micro-image:2.0`.
###
# Etapa 1: Build nativo
FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 AS build
USER root
RUN microdnf update -y && \
    microdnf install -y wget tar gzip && \
    wget -O /tmp/maven.tar.gz https://archive.apache.org/dist/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz && \
    tar xzf /tmp/maven.tar.gz -C /opt && \
    ln -s /opt/apache-maven-3.9.6 /opt/maven && \
    ln -s /opt/maven/bin/mvn /usr/local/bin/mvn && \
    rm /tmp/maven.tar.gz && \
    microdnf clean all

ENV PATH="/opt/maven/bin:${PATH}"
WORKDIR /project
COPY . .
RUN chown -R root:root /project && \
    mvn package -Dnative -DskipTests

# Etapa 2: Runtime
FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work/
COPY --from=build /project/target/*-runner /work/application
RUN chmod 755 /work/application
USER 1001
EXPOSE 8080
ENTRYPOINT ["./application","-Dquarkus.http.host=0.0.0.0"]