services:
  bd:
    image: mysql:8.0
    restart: always
    container_name: bd
    environment:
      MYSQL_DATABASE:             tmdb
      MYSQL_ROOT_PASSWORD:        root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  
  backend:
    image: task-manager-micro:latest
    restart: always
    container_name: backend
    environment:
      - USER_BD=root
      - PASSWORD_BD=root
      - DATASOURCE_BD=jdbc:mysql://bd:3306/tmdb
      - JWT_PUBLIC_KEY_PATH=file:/work/publicKey.pem
      - JWT_PRIVATE_KEY_PATH=file:/work/privateKey.pem
    ports:
      - "8080:8080"
    volumes:
      - ./privateKey.pem:/work/privateKey.pem
      - ./publicKey.pem:/work/publicKey.pem